BACKGROUND_HISTORY = 10
BUFFER_DUR = 10
EXCLUDED_CLASSES = "0"
FPS = 4
FRAME_HEIGHT = 1440
FRAME_WIDTH = 2560
IMGSZ = 640
MAX_DETS = 5
MJPEG_QV = 15
MODEL_PATH = "yolo26n_subclass_ncnn_model"
OUTPUT_DIR = "object_clips"
OUTPUT_HEIGHT = 1080
OUTPUT_WIDTH = 1920