BACKGROUND_HISTORY = 10
BUFFER_DUR = 5
CONF = 0.2
EXCLUDED_CLASSES = "0"
FPS = 4
FRAME_HEIGHT = 1296
FRAME_WIDTH = 2304
IMGSZ = 640
LOG_LEVEL = "INFO"
MAX_DETS = 5
MJPEG_QV = 5
MODEL_PATH = "yolo26n_subclass_ncnn_model"
MONITORING_FREQ = 5
OUTPUT_DIR = "object_clips"
SAVE_RAW_VIDEO = true
TRACK_HISTORY_DUR = 5
TRACK_IOU_THRESHOLD = 0.3
TRACK_NEW_TRACK_CONF_THRESHOLD = 0.4
