[package]
name = "inference_ext"
version = "0.1.0"
edition = "2021"

[lib]
name = "inference_ext"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
ultralytics-inference = { version = "0.0.35", default-features = false }
image = { version = "0.25", default-features = false }
